name = "LowRankMatrices"
uuid = "e65ccdef-c354-471a-8090-89bec1c20ec3"
authors = ["Jishnu Bhattacharya <jishnub.github@gmail.com> and contributors"]
version = "1.0.2"

[deps]
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[weakdeps]
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"

[extensions]
LowRankMatricesFillArraysExt = "FillArrays"

[compat]
Aqua = "0.8"
FillArrays = "0.6, 0.7, 0.8, 0.9, 0.10, 0.11, 0.12, 0.13, 1"
LinearAlgebra = "<0.0.1, 1"
Test = "<0.0.1, 1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test", "FillArrays"]
